# Page settings

baseURL = "https://dumortier-cv.netlify.com"
languageCode = "fr"
title = "Didier Dumortier"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

DefaultContentLanguage = "fr"

[languages]
    [languages.en]
    weight = 10
    languageName = "English"
        [languages.en.params]
            [languages.en.params.profile]
                enable = true
                name = "Didier Dumortier"
                tagline = "SI Designer"

            [languages.en.params.languages]
                enable = true
                [[languages.en.params.languages.list]]
                name = "English"
                level = "Fluent"
                [[languages.en.params.languages.list]]
                name = "German"
                level = "Fluent"


            [languages.en.params.interests]
                enable = true
                [[languages.en.params.interests.list]]
                name = "Travel with bike"
                [[languages.en.params.interests.list]]
                name = "Guitar"
                [[languages.en.params.interests.list]]
                name = "Cooking"

    [languages.fr]
    weight = 0
    languageName = "French"
#        [languages.fr.params]
#            [languages.fr.params.profile]
#                enable = true
#                name = "Didier Dumortier"
#                tagline = "Concepteur en systèmes d'information"

[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#01087C"
    textPrimaryColor = "#131826"

    postSections = "posts"

    [params.profile]
        enable = true
        name = "Didier Dumortier"
        tagline = "Concepteur en systèmes d'information"

    [params.contact]
        enable = true
        location = "Rouen"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "06 65 84 50 41"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "did.dumortier@gmail.com"
#        [[params.contact.list]]
#        icon = "fas fa-globe"
#        url = "#"
#        text = "www.yourwebsite.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "development"
        [[params.skills.list.items]]
        details = "JS/Angular"
        [[params.skills.list.items]]
        details = "PHP/Symfony"
        [[params.skills.list.items]]
        details = "Node"

        [[params.skills.list]]
        title = "cms"
        [[params.skills.list.items]]
        details = "Drupal/Wordpress/Grav"
        [[params.skills.list.items]]
        details = "Bootstrap 4/HTML5"
        [[params.skills.list.items]]
        details = "SASS/less/CSS3"
        [[params.skills.list.items]]
        details = "GIT/GitLab/GitHub"

        [[params.skills.list]]
        title = "competences"
        [[params.skills.list.items]]
        details = "communication"
        [[params.skills.list.items]]
        details = "team-working"
        [[params.skills.list.items]]
        details = "managment-project"
        [[params.skills.list.items]]
        details = "analyse-specifications"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Diplôme d'ingénieur IMA"
        university = "Ecole Polytech'Lille"
        dates = "2000 - 2003"
        [[params.education.list]]
        degree = "DEUG Mathématiques Informatique MIAS"
        university = "Universié de Rouen"
        dates = "1998 - 2000"
        [[params.education.list]]
        degree = "Hypokhâgne Sciences Sociales"
        university = "Lycée Claude Monet Le Havre"
        dates = "1997 - 1998"
        [[params.education.list]]
        degree = "Bac S"
        university = "Ecole des Pupilles de l'air Grenoble"
        dates = "1994 - 1997"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Anglais"
        level = "Courant"
        [[params.languages.list]]
        name = "Allemand"
        level = "Courant"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Voyage à vélo"
        [[params.interests.list]]
        name = "Guitare"
        [[params.interests.list]]
        name = "Cuisine"

    [params.summary]
        enable = true

    [params.experience]
        enable = true

    [params.projects]
        enable = true

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Voyage à vélo, Guitare, Cuisine"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/did1979"
        title = "did1979"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/didier-dumortier-543930157/"
        title = "didier.dumortier"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/did1979"
        title = "@did1979"





